[pytest]
# 测试发现规则
testpaths = testcase
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 测试用例参数中的中文不转义
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

# pytest捕获DEBUG及以上日志
log_level = DEBUG

# 不在测试执行过程中实时打印日志
log_cli = false

addopts =
    -v
    --no-log-file
    --html=reports/report.html
    --self-contained-html

markers =
    smoke: 冒烟测试
    regression: 回归测试
    client: 客户端接口
    management: 管理端接口